### ISSUE TITLE
ops.pebble.APIError during update events

### ISSUE THREAD

**Issue by deusebio** [canonical/spark-history-server-k8s-operator#30]
## Actual behavior

The juju debug-log stack shows some errors as the following:

```
unit-spark-history-server-k8s-0: 20:43:26 ERROR juju.worker.uniter pebble poll failed for container "spark-history-server": failed to send pebble-ready event: hook failed
unit-spark-history-server-k8s-0: 20:43:30 ERROR unit.spark-history-server-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/pebble.py", line 1599, in _request_raw
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/./src/charm.py", line 217, in <module>
    main(SparkHistoryServerCharm)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/framework.py", line 342, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/framework.py", line 839, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/framework.py", line 928, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/./src/charm.py", line 93, in _on_spark_history_server_pebble_ready
    container.add_layer(CONTAINER_LAYER, self._spark_history_server_layer, combine=True)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/model.py", line 2078, in add_layer
    self._pebble.add_layer(label, layer, combine=combine)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/pebble.py", line 1883, in add_layer
    self._request('POST', '/v1/layers', body=body)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/pebble.py", line 1564, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/pebble.py", line 1610, in _request_raw
    raise APIError(body, code, status, message)
ops.pebble.APIError: plan must define "command" for service "history-server"
unit-spark-history-server-k8s-0: 20:43:31 ERROR juju.worker.uniter.operation hook "spark-history-server-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
```

Apart from this error, the spark-history server service run fine otherwise.

## Versions

Operating system: jammy 22.04

Juju CLI: 3.1.7

Juju agent: 3.1.6

Charm revision: 3.4/edge (rev15)

microk8s: 1.29.1

**Comment by deusebio** [comment]
This is not present anymore. This can be confirmed looking at the logs of the end-to-end tests, [here](https://github.com/canonical/spark-k8s-bundle/actions/runs/8978133497)
