### ISSUE TITLE
Spark requires a new microk8s deployment

### ISSUE THREAD

**Issue by natalian98** [canonical/spark-history-server-k8s-operator#39]
When spark is deployed on a "fresh" microk8s, the following steps work, but consequent deployments on the same cluster error out on `config-changed` event. The s3 relation databag is empty then:
```
$ juju show-unit spark-history-server-k8s/0
spark-history-server-k8s/0:
  opened-ports: []
  charm: ch:amd64/jammy/spark-history-server-k8s-23
  leader: true
  life: alive
  relation-info:
  - relation-id: 1
    endpoint: s3-credentials
    related-endpoint: s3-credentials
    application-data:
      data: '{}'
```

## Steps to reproduce

```
$ git clone https://github.com/canonical/spark-history-server-k8s-operator.git
$ cd tests/integration/setup/
$ bash setup_minio.sh
s3 params setup attempt=1
access_key=F9RYYHQ9EXTDK083UKRA
secret_key=Pvjxc2RD9ASGOo41h9wdDg4jTVXXHZlhDFF0GjMr
endpoint=http://10.152.183.185:80
s3 params setup complete...
http://10.152.183.185:80,F9RYYHQ9EXTDK083UKRA,Pvjxc2RD9ASGOo41h9wdDg4jTVXXHZlhDFF0GjMr

$ export S3_ENDPOINT=http://10.152.183.185:80
$ export S3_BUCKET=history-server
$ export ACCESS_KEY=F9RYYHQ9EXTDK083UKRA
$ export SECRET_KEY=Pvjxc2RD9ASGOo41h9wdDg4jTVXXHZlhDFF0GjMr

$ juju deploy s3-integrator -n1 --channel edge
$ juju config s3-integrator bucket=$S3_BUCKET path="spark-events" endpoint=$S3_ENDPOINT
$ juju run s3-integrator/leader sync-s3-credentials access-key=$ACCESS_KEY secret-key=$SECRET_KEY

$ juju deploy spark-history-server-k8s --channel edge --trust
$ juju integrate s3-integrator spark-history-server-k8s

$ juju destroy-model ...
# deploy again
```

## Expected behavior

Spark History Server can be deployed multiple times on the same microk8s cluster.

## Actual behavior

Spark History Server can only be deployed once.

## Versions

Operating system: ubuntu 22.04

Juju CLI: 3.4

Juju agent: 3.4

Charm revision: 23

microk8s: 1.28-strict/stable

## Log output

Juju debug log: 

```
unit-spark-history-server-k8s-0: 14:15:15 INFO unit.spark-history-server-k8s/0.juju-log On config changed event.
unit-spark-history-server-k8s-0: 14:15:15 ERROR unit.spark-history-server-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/./src/charm.py", line 38, in <module>
    main(SparkHistoryServerCharm)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/main.py", line 456, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/framework.py", line 352, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/framework.py", line 865, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/framework.py", line 955, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/src/events/history_server.py", line 54, in _on_config_changed
    self.history_server.update(
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/src/managers/history_server.py", line 122, in update
    self.workload.write(config.contents, str(self.workload.paths.spark_properties))
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/src/managers/history_server.py", line 89, in contents
    dict_content = self.to_dict()
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/src/managers/history_server.py", line 84, in to_dict
    return self._base_conf | self._s3_conf | self._ingress_proxy_conf | self._auth_conf
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/src/managers/history_server.py", line 59, in _s3_conf
    "spark.hadoop.fs.s3a.access.key": s3.access_key,
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/src/core/domain.py", line 59, in access_key
    return self.relation_data["access-key"]
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/model.py", line 1697, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-spark-history-server-k8s-0/charm/venv/ops/model.py", line 796, in __getitem__
    return self._data[key]
KeyError: 'access-key'
unit-spark-history-server-k8s-0: 14:15:15 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by welpaolo** [comment]
I tried to reproduce the issue but it is not reproducible with the command you mentioned. I will close the issue for now. Please re-open it if it is happening again!
